server:
  port: 8085

spring:
  application:
    name: api-gateway

# Eureka properties
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

# Zuul properties
zuul:
  host:
    socket-timeout-millis: 30000
  routes:
    product-service: /product-service/**
    inventory-service: /inventory-service/**
